doc_ja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docja/',include('doc_ja_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doc_ja_app/urls.py
from django.urls import path
from doc_ja_app.views import *
from django.contrib.auth import views as auth_views

app_name = "doc_ja_app"


urlpatterns = [

    path('', index_view, name='index'),

    path('doctor_list/', doctor_list_view, name="doctor_list"),
    # path('doctor_list/<str:expert>', doctor_list_view, name="doctor_list_expert"),
    path('doctor_detail/<pk>', doctor_detail_view, name="doctor_detail"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/docja/password_reset/complete'),
         name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('doctor_register/', doctor_register_view, name="doctor_register"),
    path('web_user_register/', web_user_register_view, name="web_user_register"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('profile/', profile_view, name='profile'),
    path('doctor_edit/', doctor_account_edit_view, name='doctor_edit'),
    path('web_user_edit/', web_user_account_edit_view, name='web_user_edit'),

    path('doctor_like/', doctor_like, name='doctor_like'),

    path('search/', search_view, name='search'),
    path('send/comment/<pk>', doctor_comment_view, name='send_comment'),
    path('reservation/', reservation_view, name='reservation'),
    path('about_us/', about_us_view, name='about_us'),
]

templates/partiels/footer.html
        <footer class="footer container">
            <p class="footer-text">تمامی حقوق این سایت مختص به دکترجا می باشد.</p>
            <span class="footer-icons-container">
                <i class="fa-brands fa-instagram footer-icon"></i>
                <i class="fa-brands fa-whatsapp footer-icon"></i>
                <i class="fa-brands fa-x-twitter footer-icon"></i>
                <i class="fa-solid fa-phone footer-icon"></i>
                <i class="fa-solid fa-location-dot footer-icon"></i>
            </span>
        </footer>

templates/partiels/header.html
{% load static %}
<header class="header container">
            <div id="header-menu">
                <ul id="header-menu-list">
                    <li class="header-menu__item">
                        <a href="{% url 'doc_ja_app:profile' %}"><img src="{% if user.is_authenticated or profile == True %} {% if user.doctor %} {{ user.doctor.photo.url }} {% else %} {{ user.web_user.photo.url }} {% endif %} {% else %} {% static 'Assets/Images/profile-circle.png' %} {% endif %}" alt="profile-image"></a>
                    </li>
                    <li class="header-menu__item a1"><a href="{% url 'doc_ja_app:doctor_list' %}"><i class="fa-solid fa-house"></i>صفحه اصلی</a></li>
                    <li class="header-menu__item a2"><a href="{% url 'doc_ja_app:about_us' %}"><i class="fa-solid fa-circle-info"></i>درباره ما</a></li>
                    <li class="header-menu__item a2 dropdown">
                        <button class="dropbtn">ورود/ثبت نام<i class="fa fa-caret-down"></i></button>
                        <ul class="dropdown-content">
                            <li><a href="{% url 'doc_ja_app:login' %}"  class="dropdown-item">ورود</a></li>
                            <li><a href="{% url 'doc_ja_app:web_user_register' %}"  class="dropdown-item">ثبت نام کاربر</a></li>
                            <li><a href="{% url 'doc_ja_app:doctor_register' %}"  class="dropdown-item">ثبت نام پزشک</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="category-section">
                <form action="{% url 'doc_ja_app:doctor_list' %}" class="category-form" method="post">
                    <label for="category" class="category-label">.: دسته بندی :.</label>
                    <select name="field" id="category">
                        <option value="all" class="select-item">همه</option>
                        <option value="پزشک عمومی" class="select-item">پزشک عمومی</option>
                        <option value="متخصص زنان" class="select-item">متخصص زنان</option>
                        <option value="متخصص مغز و اعصاب" class="select-item">متخصص مغز و اعصاب</option>
                        <option value="متخصص مامایی" class="select-item">متخصص مامایی</option>
                        <option value="چشم پزشک" class="select-item">چشم پزشک</option>
                        <option value="متخصص گوش،حلق،بینی" class="select-item">متخصص گوش،حلق و بینی</option>
                        <option value="متخصص زیبایی" class="select-item">متخصص زیبایی</option>
                        <option value="دندانپزشک" class="select-item">دندانپزشک</option>
                        <option value="جراخ پلاستیک" class="select-item">جراح پلاستیک</option>
                        <option value="متخصص اطفال" class="select-item">متخصص اطفال</option>
                        <option value="متخصص قلب" class="select-item">متخصص قلب</option>
                        <option value="متخصص داخلی" class="select-item">متخصص داخلی</option>
                        <option value="متخصص غدد" class="select-item">متخصص غدد</option>


                    </select>
                </form>
            </div>
            <div class="search-section">
                <form action="{% url 'doc_ja_app:search' %}" id="search-menu" autocomplete="off">
                    <button type="submit" class="search-menu-submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                    <input name="query" type="search" placeholder="جستجو ..." class="search-bar">
                </form>
            </div>
        </header>

templates/partiels/header2.html
{% load static %}


        <header class="header container">
            <div id="header-menu">
                <ul id="header-menu-list">
                    <li class="header-menu__item">
                        <a href={% url 'doc_ja_app:profile' %}><img src="{% if user.is_authenticated or profile == True %} {% if user.doctor %} {{ user.doctor.photo.url }} {% else %} {{ user.web_user.photo.url }} {% endif %} {% else %} {% static 'Assets/Images/profile-circle.png' %} {% endif %}" alt="profile-image"></a>
                    </li>
                    <li class="header-menu__item a1"><a href={% url 'doc_ja_app:doctor_list' %}><i class="fa-solid fa-house"></i>صفحه اصلی</a></li>
                    <li class="header-menu__item a2"><a href='{% url 'doc_ja_app:about_us' %}'><i class="fa-solid fa-circle-info"></i>درباره ما</a></li>
                    <li class="header-menu__item a2 dropdown">
                        <button class="dropbtn">ورود/ثبت نام<i class="fa fa-caret-down"></i></button>
                        <ul class="dropdown-content">
                            <li><a href={% url 'doc_ja_app:login' %}  class="dropdown-item">ورود</a></li>
                            <li><a href={% url 'doc_ja_app:web_user_register' %}  class="dropdown-item">ثبت نام کاربر</a></li>
                            <li><a href={% url 'doc_ja_app:doctor_register' %}  class="dropdown-item">ثبت نام پزشک</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </header>