doc_ja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docja/',include('doc_ja_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doc_ja_app/urls.py
from django.urls import path
from doc_ja_app.views import *
from django.contrib.auth import views as auth_views

app_name = "doc_ja_app"


urlpatterns = [

    path('', index_view, name='index'),

    path('doctor_list/', doctor_list_view, name="doctor_list"),
    # path('doctor_list/<str:expert>', doctor_list_view, name="doctor_list_expert"),
    path('doctor_detail/<pk>', doctor_detail_view, name="doctor_detail"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/docja/password_reset/complete'),
         name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('doctor_register/', doctor_register_view, name="doctor_register"),
    path('web_user_register/', web_user_register_view, name="web_user_register"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('profile/', profile_view, name='profile'),
    path('doctor_edit/', doctor_account_edit_view, name='doctor_edit'),
    path('web_user_edit/', web_user_account_edit_view, name='web_user_edit'),

    path('doctor_like/', doctor_like, name='doctor_like'),

    path('search/', search_view, name='search'),
    path('send/comment/<pk>', doctor_comment_view, name='send_comment'),
    path('reservation/', reservation_view, name='reservation'),
    path('about_us/', about_us_view, name='about_us'),
]

templates/docja/about_us.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href={% static 'css/about-us.css' %}>
</head>
<body>
{% include "partiels/header2.html" %}
{% include "partiels/navigation.html" %}


        <section class="about-us container">
            <p class="about-us-text">سلام و خوش آمدید به سایت رزرو وقت پزشک آنلاین ما، دکترجا!<br><br> ما با افتخار به شما خدماتی بی‌نظیر در زمینه رزرو وقت پزشک آنلاین ارائه می‌دهیم. ماموریت ما این است که ارتباط بین پزشکان با بیماران را ساده و موثر کنیم تا شما بتوانید به راحتی و با اطمینان وقت خود را با پزشکان متخصص رزرو کنید. <br><br> امیدواریم که تجربه شما با سایت ما لذت بخش و مفید باشد. با ما همراه باشید، تا به شما کمک کنیم در بهبود و حفظ سلامتی خود موفق باشید! <br>برای راحتی شما عزیزان راه های ارتباطی در این بخش قرار داده شده اند. <br><br> </p>
            <span class="footer-icons-container">
                <i class="fa-brands fa-instagram footer-icon"></i>
                <i class="fa-brands fa-whatsapp footer-icon"></i>
                <i class="fa-brands fa-x-twitter footer-icon"></i>
                <i class="fa-solid fa-phone footer-icon"></i>
                <i class="fa-solid fa-location-dot footer-icon"></i>
            </span>
        </section>

</body>
</html>

templates/docja/ajaxlist.html
       {% load static %}

            {% for doctor in doctors %}
            <div class="doctors-list-item">
                <span class="doctors-list-item-header">
                    <img src="{{ doctor.photo.url }}" alt="profile-image">
                    <p class="doctor-name"> {{ doctor.user.first_name }} </p>
                </span>
                <p class="dotcor-expertise">{{ doctor.expert }}</p>
                <span class="likes">
                    <p>تعداد لایک ها</p>
                    <span>{{ doctor.likes.count }}<i class="fa-regular fa-thumbs-up"></i></span>
                </span>
                <a href="{% url 'doc_ja_app:doctor_detail' doctor.id %}"><button class="more-btn">رزرو و اطلاعات بیشتر</button></a>
            </div>
            {% endfor %}

templates/docja/doctor_detail.html
{% extends 'parent/base2.html' %}
{% load static %}

{% block head %} <link rel="stylesheet" href="{% static 'css/doctor-profile.css' %}"> {% endblock %}

{% block title %} Doctor Profile {% endblock %}

{% block content %}

        <section class="doctor-profile-section container">
            <div class="doctor-profile-title">
                <img src="{{ doctor.photo.url }}" alt="post-image">
                <h3 class="doctor-name">{{ doctor.user.first_name }}</h3>
            </div>
            <div class="doctor-profile-texts">
                <h6 class="texts-title">توضیحات</h6>
                <p class="doctor-profile-description">
                    {{ doctor.description }}
                </p>
                <h6 class="texts-title">آدرس مطب</h6>
                <p class="address">
                    {{ doctor.address }}
                </p>
                <h6 class="texts-title">رزرو وقت</h6>
                <p class="reservation-text">روز و ساعت مورد نظر خود جهت رزرو وقت را انتخاب کنید :</p>
                <div class="reservation">
                    <form action="#" autocomplete="off" id="form1">
                        <span class="divider">
                            <input type="radio" name="days" value="شنبه" class="reservation-input" id="radio-0">
                            <label for="radio-0">شنبه</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="days" value="یک شنبه" class="reservation-input" id="radio-1">
                            <label for="radio-1">یک شنبه</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="days" value="دوشنبه" class="reservation-input" id="radio-2">
                            <label for="radio-2">دوشنبه</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="days" value="سه شنبه" class="reservation-input" id="radio-3">
                            <label for="radio-3">سه شنبه</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="days" value="چهارشنبه" class="reservation-input" id="radio-4">
                            <label for="radio-4">چهارشنبه</label>
                        </span>
                    </form>
                    <form action="#" autocomplete="off" id="form2">
                        <span class="divider">
                            <input type="radio" name="hours" value="91" class="reservation-input" id="radio-91">
                            <label for="radio-91">09:00</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="hours" value="92" class="reservation-input" id="radio-92">
                            <label for="radio-92">09:30</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="hours" value="101" class="reservation-input" id="radio-101">
                            <label for="radio-101">10:00</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="hours" value="102" class="reservation-input" id="radio-102">
                            <label for="radio-102">10:30</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="hours" value="111" class="reservation-input" id="radio-111">
                            <label for="radio-111">11:00</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="hours" value="112" class="reservation-input" id="radio-112">
                            <label for="radio-112">11:30</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="hours" value="121" class="reservation-input" id="radio-121">
                            <label for="radio-121">12:00</label>
                        </span>
                        <span class="divider">
                            <input type="radio" name="hours" value="122" class="reservation-input" id="radio-122">
                            <label for="radio-122">12:30</label>
                        </span>
                        <button data-doctor-id="{{ doctor.id }}" type="submit" class="reservation-submit-btn">ثبت رزور وقت</button>
                    </form>
                </div>
            </div>
            <div class="comment-section">
                <h2 class="comment-section-title">ارسال نظر</h2>
                <form action="{% url 'doc_ja_app:send_comment' doctor.id %}" class="form" autocomplete="off" method="post">
                    {% csrf_token %}
                    <input name="name" type="text" class="input" placeholder="نام و نام خانوادگی" required minlength="3" maxlength="25">
                    <input name="email" type="email" class="input "placeholder="ایمیل" required>
                    <textarea name="message" id="text-area" cols="25" rows="10" placeholder="نظرات ..." required></textarea>
                    <button type="submit" class="comment-btn">ارسال</button>
                </form>
            </div>
            <div class="like-section" data-doctor-id="{{ doctor.id }}">
                <p class="like-section-text">اگر از این پزشک راضی هستید، پروفایل پزشک را لایک کنید :</p>
                <span ><span id="like_count">{{ doctor.likes.count }}</span><i class="fa-regular fa-thumbs-up" id="like_button"></i></span>
            </div>
            <div class="previous-comments-section">
                <h6 class="previous-comments-title">نظرات</h6>
                {% for comment in comments %}
                <div class="comment">
                    <p class="comment-username">{{ comment.name }}</p>
                    <p class="comment-text">{{ comment.message }}</p>
                    <span class="comment-date">{{ comment.created }}</span>
                </div>
                    {% empty %}
                    <p>کامنتی وجود ندارد</p>
                {% endfor %}

            </div>
        </section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function (){
        $('#like_button').click(function (){
            var doctor_id = $('.like-section').data('doctor-id');
            var button = $(this);
            var csrftoken = '{{csrf_token}}';


            $.ajax({
                type: 'POST',
                url: '/docja/doctor_like/',
                data: {'doctor_id': doctor_id, 'csrfmiddlewaretoken': csrftoken },
                success: function(data) {

                    $('#like_count').text(data.like_count);
                },
            });
        });



        $('.reservation-submit-btn').click(function (){
            console.log('ok');
            var doctor_id = $('.reservation-submit-btn').data('doctor-id');
            var button = $(this);
            var csrftoken = '{{csrf_token}}';
            var day;
            var hour;

            for( let i=0; i<=4; i++){
                 let idd = "radio-" + i.toString();
                const radio = document.getElementById(idd)
                if(radio.checked){
                    day = radio.value;
                }
            }
            const numbers = [91,92,101,102,111,112,121,122]
            for( let x=0; x < numbers.length; x++){
                 let idd = "radio-" + numbers[x].toString();
                const radio = document.getElementById(idd)
                if(radio.checked){
                    hour = radio.value;
                }
            }

            $.ajax({
                type: 'POST',
                url: '/docja/reservation/',
                data: {'hour': hour,'day': day,'doctor_id': doctor_id, 'csrfmiddlewaretoken': csrftoken },
                dataType: "json",
                success: function(data) {

                    if (data.status){
                        alert('با موفقیت رزرو شد')
                    }
                    else{
                        alert('زمان انتخابی پر است')
                    }
                },
            });
        });









    });



</script>
{% endblock %}

templates/docja/doctor_list.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %} DOC JA{% endblock %}

{% block content %}

    <section class="image-section container">
            <div class="hidden"></div>
            <div class="logo-section">
                <h1>دکترجا</h1>
                <img src="{% static "Assets/Images/IMG_20240416_181701_480.png" %}" alt="background-image">
                <div class="shoar">
                    <p>بهبودی شما آرزوی ماست</p>
                    <p id="shoar-last">سلامت شما هدف ماست</p>
                </div>
            </div>
        </section>
    <div class="doctors-list-title container">
        <h6 id="title">لیست پزشکان</h6>
    </div>


       <section class="doctors-list-section container" id="ttt">
            {% for doctor in doctors %}
            <div class="doctors-list-item">
                <span class="doctors-list-item-header">
                    <img src="{{ doctor.photo.url }}" alt="profile-image">
                    <p class="doctor-name"> {{ doctor.user.first_name }} </p>
                </span>
                <p class="dotcor-expertise">{{ doctor.expert }}</p>
                <span class="likes">
                    <p>تعداد لایک ها</p>
                    <span>{{ doctor.likes.count }}<i class="fa-regular fa-thumbs-up"></i></span>
                </span>
                <a href="{% url 'doc_ja_app:doctor_detail' doctor.id %}"><button class="more-btn">رزرو و اطلاعات بیشتر</button></a>
            </div>
            {% endfor %}

        </section>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
$(".category-form").on("change", function(){
  var selectedValue = $('#category').val();
  console.log(selectedValue);


  $.ajax({
    url : "{% url 'doc_ja_app:doctor_list' %}",
    type : "GET",
      data : {'expert': selectedValue},
    dataType : "html",
      success : function (data){

           $('#ttt').html(data);


      }

  });
});
</script>

{% endblock %}

templates/docja/doctor_profile.html
{% extends 'parent/base2.html' %}
{% load static %}

{% block title %} profile{% endblock %}
{% block head %} <link rel="stylesheet" href={% static 'css/user-doctor-information.css' %}> {% endblock %}
{% block content %}
        <section class="information-container container">
            <div class="information-section">
                <span class="information-title">نام و نام خانوادگی</span>
                <p class="information-text">{{ own_user.user.first_name }}</p>
                <span class="information-title">نام کاربردی</span>
                <p class="information-text">{{ own_user.user.username }}</p>
                <span class="information-title">رمز عبور</span>
                <p class="information-text">********</p>
                <span class="information-title">شماره نظام پزشکی</span>
                <p class="information-text">{{ own_user.mc_number }}</p>
                <span class="information-title">شماره تلفن همراه</span>
                <p class="information-text">{{ own_user.phone }}</p>
                <span class="information-title">ایمیل</span>
                <p class="information-text">{{ own_user.user.email }}</p>
                <span class="information-title">آدرس مطب</span>
                <p class="information-text">{{ own_user.address }}</p>
                <span class="information-title">تخصص</span>
                <p class="information-text">{{ own_user.expert }}</p>
                <span class="information-title">توضیحات</span>
                <p class="information-text">{{ own_user.description }}</p>
                <div class="button-section">
                    <a href="{% url 'doc_ja_app:doctor_edit' %}"><button class="btn edit-btn">ویرایش اطلاعات</button></a>
                    <a href="{% url 'doc_ja_app:logout' %}"><button class="btn logout-btn">خروج از اکانت</button></a>
                </div>
            </div>
        </section>


{% endblock %}

templates/docja/index.html
{% extends 'parent/base.html' %}

{% block title %} DOC JA{% endblock %}

{% block content %}

 <p>body</p>


{% endblock %}

templates/docja/web_user_profile.html
{% extends 'parent/base2.html' %}
{% load static %}

{% block title %}Profile{% endblock %}
{% block head %} <link rel="stylesheet" href={% static 'css/user-doctor-information.css' %}> {% endblock %}

{% block content %}

        <section class="information-container container">
            <div class="information-section">
                <span class="information-title">نام و نام خانوادگی</span>
                <p class="information-text">{{ own_user.user.first_name }}</p>
                <span class="information-title">نام کاربردی</span>
                <p class="information-text">{{ own_user.user.username }}</p>
                <span class="information-title">رمز عبور</span>
                <p class="information-text">********</p>
                <span class="information-title">شماره تلفن همراه</span>
                <p class="information-text">{{ own_user.phone }}</p>
                <span class="information-title">ایمیل</span>
                <p class="information-text">{{ own_user.user.email }}</p>
                <div class="button-section">
                    <a href="{% url 'doc_ja_app:web_user_edit' %}"><button class="btn edit-btn">ویرایش اطلاعات</button></a>
                    <a href="{% url 'doc_ja_app:logout' %}"><button class="btn logout-btn">خروج از اکانت</button></a>
                </div>
            </div>
        </section>


{% endblock %}